### ISSUE TITLE
On blur option?

### ISSUE THREAD

**Issue by villelahdenvuo** [maxisam/ngx-trim#1]
Currently if I'm editing the text field and want to add something to the end and I press space the space is removed right away so to add spaces I need to write something and go back to add spaces.

This UX issue would be solved if trimming only happened on the blur event.

**Comment by maxisam** [comment]
You are welcome to make a pull request. Currently, I got swamped with work, so I won't be able to do anything.

**Comment by villelahdenvuo** [comment]
It's okay, I found an alternative that supports it. https://github.com/anein/angular2-trim-directive
